boostcampwm-2021/web03-boocamWiki

.github/ISSUE_TEMPLATE/-------.md

이슈 템플릿 업데이트

---

.github/ISSUE_TEMPLATE/-------.md

[Chore] 이슈템플릿 생성

---

client/src/header/Header.jsx
client/src/section/Section.jsx
client/src/section/mainpage/mainSection.jsx
client/src/section/sidepage/rankSection.jsx
client/src/section/sidepage/recentSection.jsx

- NAV 메뉴바 수정
- 섹션의 정렬과 위치 수정
#6

feat: 메인페이지 레이아웃 수정

---

server/src/config/index.ts

- express bulletproof 아키텍쳐 구현
- 폴더별 더미 파일 생성
#29

chore: express bulletproof 아키텍쳐 구현

---

server/package-lock.json
server/package.json
server/src/api/documents.ts
server/src/sql/documents-query.ts
server/src/types/apiInterface.ts

- /documents/search api 생성
- generation, boostcamp_id, name 확인
- validator는 추후생성 예정
#19

feat: search api 생성

---

client/.eslintrc.js
client/src/components/make-section/MakeSection.jsx
client/src/components/make-section/make-section-components/InputTitle.jsx

- 내용 입력 이후에 버튼을 통해 중복 체크 가능
- 중복 체크 이후 제목을 변경할 경우 중복체크 여부를 초기화 시키도록 구현
#18

feat: 문서 작성 페이지 제목 중복 체크 기능 구현

---

client/src/components/make-section/MakeSection.jsx
client/src/components/make-section/make-section-components/InputTitle.jsx
server/src/loaders/express.ts

feat: 문서 작성 구현

---

client/.eslintrc.js

fix: client 내 .eslintrc.js 수정

---

server/src/sql/documents-query.ts

- group by 절 사용
- max aggregate 함수 사용
#16

feat : 최근 변경 문서api query 업데이트

---

client/.eslintrc.js
client/src/App.css
client/src/App.tsx
client/src/components/main-section/MainSection.jsx
client/src/pages/ErrorPage.jsx
client/src/styles/ErrorPage.module.scss
client/src/styles/global.scss
server/src/api/documents.ts
server/src/sql/documents-query.ts

feat: error page 생성, 문서 열람 API 추가

---

client/src/components/make-section/MakeSection.jsx
client/src/pages/makePage.jsx
server/package-lock.json
server/src/sql/documents-query.ts

- 문서를 생성하고 등록하면 DB에 저장
- API를 사용하여 저장하도록 구현
- 생성이 완료되면 이전 화면으로 돌아가도록 처리
#18

feat: 문서 생성 API 구현

---

server/package-lock.json
server/package.json
server/src/api/documents.ts
server/src/loaders/express.ts
server/src/services/login.ts

- 패스워드 생성 함수 추가
- cors 모듈 삭제
- result 개수가 0개일 시 로직 추가

feat: 패스워드 생성 함수 추가

---

client/src/components/side-section/SideSection.jsx
client/src/components/side-section/side-section-components/SectionItem.jsx
server/src/api/documents.ts
server/src/sql/documents-query.ts

feat : 최근 변경 문서 사항 기능 구성

---

server/src/sql/documents-query.ts

fix: 변경 사항 순위 시간순서로 변경

---

server/src/api/documents.ts
server/src/sql/documents-query.ts
server/src/types/apiInterface.ts

- refactor: Partial을 사용하여 documentsSearch 타입 수정
- feat: search API content 추가
#60

feat: search API content 추가

---

client/src/components/make-section/MakeSection.jsx
client/src/components/make-section/make-section-components/Editor.jsx
client/src/components/make-section/make-section-components/EditorWithPreview.jsx
client/src/components/make-section/make-section-components/InputTitle.jsx
client/src/components/make-section/make-section-components/Preview.jsx

feat, refactor 분류 상태 추가, 분류 상태를 위한 리팩토링 진행

---

client/package-lock.json
client/package.json
client/src/components/side-section/side-section-components/SectionItem.jsx
client/src/components/side-section/side-section-components/SectionListGenerator.tsx
client/src/components/side-section/side-section-components/SectionListItem.tsx
client/src/types/api-document.ts

feat : #16, #17 리스트아이템 컴퍼넌트 스타일링

---

client/src/components/make-section/make-section-components/InputTitle.jsx

- 마스터, 운영진을 선택한 다음 제목을 수정하려고 할 때 발생하던 에러
수정
#18

fix: 문서 생성 분류 버그 수정

---

client/src/components/make-section/MakeSection.jsx
client/src/components/make-section/make-section-components/DocCard.jsx

- 문서 명함에 들어가는 정보들에 대한 입력란 제공
- 해당 데이터를 DB에 저장 확인
#18

feat: 문서 명함 기능 구현

---

client/src/components/side-section/SideSection.jsx
client/src/components/side-section/side-section-components/SectionItem.jsx

feat : #16, #17 사이드 섹션 아이템 개수 제한

---

client/package-lock.json
client/package.json
client/src/App.tsx
client/src/components/header/header-components/HeaderSearchBar.jsx
client/src/components/header/header-components/Logo.jsx
client/src/components/search-section/SearchSecion.jsx
client/src/pages/ErrorPage.jsx
client/src/pages/SearchPage.jsx
server/src/api/documents.ts
server/src/sql/documents-query.ts
server/src/types/apiInterface.ts

- search API에 limit, offset 파라미터 추가
- 404 페이지 오타 수정
- search 페이지 접근 시 fetch를 이용하여 값을 얻어온 후 렌더링 구현
- GNB 검색창에 이벤트 추가하여 검색 시 search 페이지로 리다이렉트
#60

feat: search API 변경 및 search 페이지 리다이렉트 구현

---

client/src/App.tsx
client/src/components/side-section/side-section-components/SectionListGenerator.tsx
client/src/components/side-section/side-section-components/SectionListItem.tsx
client/src/components/wiki-section/WikiSection.jsx
client/src/pages/makePage.jsx
client/src/pages/wikiPage.jsx

feat : #57, #16 사이드 섹션에서 문서열람

---

client/src/components/header/Header.jsx
client/src/components/header/header-components/HeaderMenu.jsx
client/src/components/make-section/make-section-components/DocCard.jsx

- 제목과 입력란이 개행을 통해 나타나던 것을 한 줄에 나타나도록 처리
#18

style: 문서 작성 페이지 명함 입력 양식 스타일 변경

---

client/src/components/side-section/SideSection.jsx
client/src/components/side-section/side-section-components/SectionItem.jsx
client/src/types/api-document.ts
server/src/api/documents.ts
server/src/sql/documents-query.ts
server/src/subscribers/document-subscriber.ts

- 열람시 sql 삽입
- 해당 기간 해당 문서 기 존재할 시 count + 1 수정
- 해당 기간 해당 문서 존재하지 않을시 count =1 삽입
- 조회수 요청반환 api 작성
- 사이드섹션 조회수 순위 출력

feat : #17 사이드섹션- 조회수 순위 출력

---

client/src/components/header/header-components/HeaderSearchBar.jsx
client/src/components/search-section/SearchSection.jsx
client/src/components/search-section/search-section-components/ResultContent.jsx
client/src/components/search-section/search-section-components/ResultFooter.jsx
client/src/components/search-section/search-section-components/ResultSummary.jsx
client/src/components/search-section/search-section-components/ResultView.jsx
server/src/api/documents.ts
server/src/sql/documents-query.ts

- 검색결과 페이지 레이아웃 작성
- document count API 추가
#60

feat: 검색결과 페이지 레이아웃 및 API 추가

---

client/src/components/main-section/MainSection.jsx
client/src/components/side-section/SideSection.jsx
client/src/components/side-section/side-section-components/SectionItem.jsx
client/src/components/side-section/side-section-components/SectionListGenerator.tsx
client/src/components/side-section/side-section-components/recents/RecentItem.tsx
client/src/components/side-section/side-section-components/top-views/TopViewItem.tsx

- 라우팅시 정상적으로 fetch 해오도록 수행
- 최신/조회수 아이템 코드 분리
- 글 길이 길 시 조치
close #17

feat : #16, #17 사이드섹션 완료

---

client/src/components/search-section/search-section-components/ResultContent.jsx
client/src/components/side-section/side-section-components/recents/RecentItem.tsx
client/src/components/side-section/side-section-components/top-views/TopViewItem.tsx
client/src/components/wiki-section/WikiSection.jsx
client/src/types/api-document.ts
client/src/utils/documents.js
client/src/utils/index.js

- Utils 생성
문서 제목 양식 함수 추가
검색 페이지에도 코드 변경하여 적용하였습니다. 확인 부탁드립니다.
mention : @0xsuky

feat : 문서 제목 util 함수 추가

---

client/src/components/WikiContentsIndex.jsx
client/src/components/make-section/MakeSection.jsx
client/src/components/wiki-section/WikiSection.jsx

feat : #57 목차 기능 구현

---

client/src/components/WikiContentsIndex.jsx
client/src/components/wiki-section/WikiSection.jsx

fix : 목차 컴퍼넌트 마진 제거

---

client/src/components/make-section/MakeSection.jsx
client/src/components/make-section/make-section-components/DocCard.jsx
client/src/components/make-section/make-section-components/Editor.jsx
client/src/components/make-section/make-section-components/EditorBox.jsx
client/src/components/make-section/make-section-components/EditorWithPreview.jsx
client/src/components/make-section/make-section-components/InputTitle.jsx
client/src/components/make-section/make-section-components/Preview.jsx

style: 문서 작성 페이지, 에디터 레이아웃 변경

---

client/src/components/search-section/search-section-components/ResultContent.jsx
client/src/components/search-section/search-section-components/ResultFooter.jsx
client/src/components/search-section/search-section-components/ResultSummary.jsx
client/src/components/search-section/search-section-components/ResultView.jsx
client/src/components/side-section/side-section-components/SectionItem.jsx
client/src/components/side-section/side-section-components/SectionListGenerator.tsx
client/src/components/side-section/side-section-components/recents/RecentItem.tsx
client/src/components/side-section/side-section-components/top-views/TopViewItem.tsx
client/src/components/wiki-section/WikiSection.jsx
client/src/pages/WikiPage.jsx
client/src/types/api-document.ts
client/src/utils/documents.js

- 내용 검색 시 하이라이트 추가
- IDocument 인터페이스 수정
- 검색 페이지 footer 수정
#60

feat: 내용 검색 시 highlight 및 검색 페이지 footer 수정 

---

client/src/components/SectionTitle.jsx
client/src/components/main-section/MainSection.jsx
client/src/components/make-section/make-section-components/DocCard.jsx
client/src/components/make-section/make-section-components/InputTitle.jsx
client/src/components/wiki-section/WikiSection.jsx
client/src/components/wiki-section/wiki-section-components/WikiCard.jsx

feat: 문서 열람 페이지 명함 구현, input placeholder 내용 제거 구현

---

client/src/components/search-section/SearchSection.jsx
client/src/components/search-section/search-section-components/ResultFooter.jsx

- 검색 결과 페이지 react key 오류 수정
- SearchSection Main width 변경
- 캠퍼ID 검색 시 오류 해결
#60

fix: 검색 페이지 오류 수정

---

client/src/components/header/header-components/HeaderSearchBar.jsx
client/src/components/header/header-components/HeaderUser.jsx
client/src/components/select-modal/SelectModal.jsx
client/src/pages/MainPage.jsx

feat: modal 컴포넌트 추가, 검색 모달 추가, 유저 모달 추가

feat: modal 컴포넌트 추가, 검색 모달 추가, 유저 모달 추가

---

client/src/components/make-section/make-section-components/InputTitle.jsx

- 일분 readonly 부분도 바뀌던 것들을 수정
#18

fix: placeholder 내용 변경

---

client/.eslintrc.js
client/package-lock.json
client/package.json
client/src/App.tsx
client/src/components/SectionTitle.jsx
client/src/components/header/Header.jsx
client/src/components/header/header-components/HeaderMenu.jsx
client/src/components/header/header-components/HeaderSearchBar.jsx
client/src/components/header/header-components/HeaderUser.jsx
client/src/components/header/header-components/Logo.jsx
client/src/components/main-section/MainSection.jsx
client/src/components/make-section/MakeSection.jsx
client/src/components/make-section/make-section-components/Editor.jsx
client/src/components/make-section/make-section-components/EditorBox.jsx
client/src/components/make-section/make-section-components/EditorWithPreview.jsx
client/src/components/make-section/make-section-components/InputTitle.jsx
client/src/components/make-section/make-section-components/WikiContentsIndex.jsx
client/src/components/select-modal/SelectModal.jsx
client/src/components/side-section/SideSection.jsx
client/src/components/side-section/side-section-components/SectionItem.jsx
client/src/components/side-section/side-section-components/SectionListGenerator.tsx
client/src/components/side-section/side-section-components/recents/RecentItem.tsx
client/src/components/side-section/side-section-components/top-views/TopViewItem.tsx
client/src/components/wiki-section/WikiSection.jsx
client/src/event-handler/select-handler.ts
client/src/magic-number.ts
client/src/reducer/doc-data-reducer.ts
client/src/reducer/select-toggle-reducer.ts
client/src/reducer/select-type-reducer.ts
client/src/styles/scss/ErrorPage.module.scss

- custom-select 생성
- 헤더&메인 반응형 UI 구현
- CSS 디자인 및 버그 수정
- eslint camel case 오류 제외 설정
- reducer dir 생성
- 공용 styled component 파일 만들기
- 매직 넘버 없애기
- Alias 알아보기... (배포 방법 결정 후)
- ts 파일에서 any 없애기...
- 공용 파일 위치 수정 및 디렉토리 구조 점검( ex. SectionTitle.jsx )

Feat: custom-select 생성, 헤더&메인 반응형 UI 구현, CSS 디자인 및 버그 수정

---

client/src/components/search-section/SearchSection.jsx
client/src/components/side-section/side-section-components/SectionItem.jsx

fix: 서버 코드 리팩토링 후 일어난 사이드 이펙트 제거

---

client/src/components/main-door/MainDoor.jsx
client/src/components/make-section/MakeSection.jsx
client/src/components/make-section/UpdateSection.jsx
client/src/components/make-section/make-section-components/InputTitle.jsx
client/src/components/search-section/SearchSection.jsx
client/src/components/side-section/side-section-components/recents/RecentItem.tsx
client/src/components/side-section/side-section-components/top-views/TopViewItem.tsx
client/src/components/wiki-section/WikiSection.jsx
docker/config.sh
docker/docker-compose.yml
docker/nginx/nginx/conf.d/default.conf
docker/nginx/nginx/fastcgi_params
docker/nginx/nginx/mime.types
docker/nginx/nginx/nginx.conf
docker/nginx/nginx/scgi_params
docker/nginx/nginx/uwsgi_params
server/package-lock.json
server/package.json
server/src/loaders/express.ts

- server API 라우팅 주소 변경 및 빌드 스크립트 추가
- docker 세팅한 폴더 추가
#104

chore: 도커 관련 세팅

---

client/package.json
docker/config.sh
docker/docker-compose.yml
docker/nginx/nginx/conf.d/default.conf
server/package.json

- CI/CD 배포를 위하여 docker-compose.yml을 비롯하여 빌드 파일 수정
#104

chore: 도커 환경설정 수정

---

client/src/components/common/MdParser.jsx
client/src/components/make-section/make-section-components/DocCard.jsx
client/src/components/make-section/make-section-components/Editor.jsx
client/src/components/make-section/make-section-components/EditorWithPreview.jsx
client/src/components/wiki-section/wiki-section-components/WikiCard.jsx
client/src/services/image-upload.js
client/src/utils/validator.js

사용자는 문서에 이미지를 업로드 할 수 있다.
-  다수의 이미지 드래그시 업로드 처리 
-  이미지 타입이 아닌 파일시 유효성처리
-  이미지 파일이 용량초과시 유효성처리
-  이미지 업로드와 관련하여 코드 리팩토링
close #94

Feature : #94 다수의 업로드 이미지 처리와 코드 리팩토링

---

client/package-lock.json
client/package.json
docker/nginx/nginx/conf.d/default.conf

chore: nginx 환경 설정 변경

---

.github/workflows/deploy.yml

feat: github-action script 작성

---

client/package.json
server/package.json

- package.json postbuild 스크립트 수정

chore: package.json postbuild 스크립트 수정

---

.gitignore

feat: gitignore 빌드 폴더 추가

---

client/public/index.html
client/src/App.tsx
client/src/components/custom-alert/AlertModal.jsx
client/src/components/header/header-components/HeaderMenu.jsx
client/src/components/make-section/MakeSection.jsx
client/src/components/make-section/make-section-components/InputTitle.jsx
client/src/components/make-section/make-section-components/input-title-components/BoostCampId.jsx
client/src/components/make-section/make-section-components/input-title-components/CreateBtn.jsx
client/src/components/make-section/make-section-components/input-title-components/Generation.jsx
client/src/components/make-section/make-section-components/input-title-components/style.js
client/src/reducer/doc-data-reducer.ts
client/src/resource/img/close.svg

- 문서 중복 검사 시, 값이 없는 경우에는 값을 입력하세요 안내 메시지를 추가했습니다.
- 문서 생성 버튼 클릭시 편집기 안에 내용이 없는 경우를 추가하여 custom-alert 로 대체하였습니다.
- 스크롤 이벤트 발생 시, select off 이벤트 추가했습니다.
#119 
- 커스텀 alert가 스크롤이 먹습니다... ㅜ

feat: 생성 시 유효성 검사 추가, custom-modal 컴포넌트, css detail 수정

---

client/src/components/make-section/MakeSection.jsx
client/src/components/make-section/make-section-components/InputTitle.jsx
client/src/components/make-section/make-section-components/input-title-components/style.js
client/src/components/select-modal/SelectModal.jsx

feat: 문서 생성 페이지 유효성 검사, css 수정

---

docker/nginx/nginx/conf.d/default.conf

- nginx 설정에 인증서 발급을 위한 추가 설정 추가

nginx certbot location 추가

---

client/package-lock.json
client/src/components/category-section/CategorySection.jsx
client/src/components/make-section/make-section-components/input-title-components/DocName.jsx
client/src/components/wiki-section/WikiSection.jsx
client/src/components/wiki-section/wiki-section-components/WikiCard.jsx
server/package-lock.json
server/package.json
server/src/api/categories.ts
server/src/api/documents.ts
server/src/services/util.ts
server/src/services/words.ts

-  분류 페이지 진입시 초성 또는 첫글자 순으로 분류하여 보여줌
-  한글 자모 분석 `hangul js` 추가
-  문서에 여러 분류 있을 때 여러 분류 보이도록 정확한 
-  검색 중 runtime 에러 발생 버그 픽스
없습니다.
항상 감사합니다~

fix, feat : 분류 페이지 작업 진행 중 및 기능 버그 픽스

---

client/src/components/category-section/CategorySection.jsx
client/src/components/category-section/style.jsx
client/src/components/search-section/SearchSection.jsx
client/src/components/search-section/search-section-components/ResultFooter.jsx
client/src/components/search-section/search-section-components/ResultView.jsx
server/src/api/categories.ts
server/src/api/documents.ts
server/src/sql/classification-query.ts

검색 페이지, 분류 페이지 테스트 완료하였습니다.
선택된 페이지를 스타일링 해보았습니다.
- close #141

feat : 분류페이지 구현

---

client/src/components/make-section/MakeSection.jsx
client/src/components/make-section/UpdateSection.jsx
client/src/components/search-section/SearchSection.jsx
client/src/components/wiki-section/WikiSection.jsx
client/src/pages/ErrorPage.jsx
client/src/pages/WikiPage.jsx
server/src/api/documents.ts
server/src/sql/documents-query.ts
server/src/types/apiInterface.ts

- 문서 동시 작성, 동시 편집에 관한 안내문 제시
- 라우팅 처리
- /w/...없는 문서목록 => 이름 '...'로 검색하셨습니까? 검색페이지 표출
- /w/...양식이 잘못된 경우 => 이름 ''로 검색하셨습니까? 검색페이지 표출
- 404 페이지
- 이전페이지로 가기
- 부캠위키 홈으로 가기

feature : 문서 동시성 검사 및 라우팅 주소와 관련하여 에러 라우팅 처리

---

client/package-lock.json
client/package.json
client/src/components/header/header-components/HeaderUser.jsx
client/src/components/join-section/join-section-components/AgreementButton.jsx
client/src/components/login-section/LoginSection.jsx
client/src/components/make-section/MakeSection.jsx
client/src/components/make-section/UpdateSection.jsx
client/src/event-handler/select-handler.ts
client/src/pages/GithubCallbackPage.jsx
client/src/pages/JoinPage.jsx
client/src/pages/MainPage.jsx
client/src/pages/MakePage.jsx
client/src/pages/UpdatePage.jsx
client/src/services/image-upload.js
client/src/styles/scss/CallbackPage.module.scss
client/src/utils/login.js
server/src/api/auth.ts
server/src/api/documents.ts
server/src/api/images.ts
server/src/api/middleware.ts

- 클라이언트 내 권한 관련 로직 작업 완료
- 백엔드 내 권한 관련 로직 작업 원료
- 권한이 필요한 작업의 경우 클라이언트는 authFetch, 서버는 jwtAuthCheck를 이용하여 검증
#52 
#55

feat: 권한 관련 로직 작업 완료

---

client/src/utils/login.js
server/src/api/documents.ts
server/src/services/login.ts
server/src/services/util.ts
server/src/sql/documents-query.ts
server/src/types/apiInterface.ts

- refreshToken 로직 수정 (구조분해할당 오류)
- 문서 update 시 ip 입력하도록 구현
#134 
#158

fix: 15분 이상 로그인 시 로그인 관련 에러 버그 수정

---

client/src/App.tsx
client/src/components/alert-confirm/AlertConfirm.jsx
client/src/components/make-section/MakeSection.jsx
client/src/components/make-section/UpdateSection.jsx
client/src/components/make-section/make-section-components/Editor.jsx
client/src/components/make-section/make-section-components/EditorBox.jsx
client/src/components/make-section/make-section-components/EditorWithPreview.jsx
client/src/components/rank-section/RankSection.jsx
client/src/components/rank-section/rank-components/ContributionRank.jsx
client/tsconfig.json
server/src/api/rank.ts
server/src/sql/rank-query.ts

feat: 수정 시, 뒤로가기 시 Confirm 창 구현, 기여도 데이터 받아오는 로직 추가

---

client/src/components/category-section/CategorySection.jsx

hotfix : 분류페이지 네비게이션 정상동작안함 처리

---

client/src/components/category-section/CategorySection.jsx

분류 페이지서 페이지네이션 query 보내지 않음 처리

[DEPOY5] hotfix배포

---

client/public/index.html
client/src/components/header/header-components/HeaderMenu.jsx
client/src/components/header/header-components/HeaderSearchBar.jsx
client/src/components/header/header-components/HeaderUser.jsx
client/src/components/header/header-components/Logo.jsx
client/src/components/side-section/side-section-components/SectionListGenerator.tsx
client/src/components/side-section/side-section-components/banners/Banners.tsx

img에 alt 속성 추가와 meta 태그 추가하였습니다. : ) 
- 라이트하우스 접근성 점수 개선
- html meta 태그 추가

perf : 라이트하우스 접근성 점수 및 SEO 개선

---

.github/workflows/dev-deploy.yml
client/public/index.html
client/src/components/category-section/CategorySection.jsx
client/src/components/header/header-components/HeaderMenu.jsx
client/src/components/header/header-components/HeaderSearchBar.jsx
client/src/components/header/header-components/HeaderUser.jsx
client/src/components/header/header-components/Logo.jsx
client/src/components/side-section/side-section-components/SectionListGenerator.tsx
client/src/components/side-section/side-section-components/banners/Banners.tsx

- 라이트하우스 접근성 점수 개선
- html meta 태그 추가

[DEPLOY] 12.05
